nvim_create_user_command('EditSymbol', function()
    vim.lsp.buf.rename()
    -- immediately save everything
    vim.api.nvim_command("wa")
end)
nvim_create_user_command('SymbolImplementation', function()
    vim.lsp.buf.implementation()
end)
nvim_create_user_command('SymbolReferences', function()
    vim.lsp.buf.references()
end)
nvim_create_user_command('SymbolTypeDef', function()
    vim.lsp.buf.type_definition()
end)
nvim_create_user_command('ListSymbols', function()
    vim.lsp.buf.document_symbol()
end)
