vim.api.nvim_create_user_command('RenameSymbol', function()
    vim.lsp.buf.rename()
end, {})
vim.api.nvim_create_user_command('SymbolImplementation', function()
    vim.lsp.buf.implementation()
end, {})
vim.api.nvim_create_user_command('SymbolReferences', function()
    vim.lsp.buf.references()
end, {})
vim.api.nvim_create_user_command('SymbolTypeDef', function()
    vim.lsp.buf.type_definition()
end, {})
vim.api.nvim_create_user_command('ListSymbols', function()
    vim.lsp.buf.document_symbol()
end, {})
