require("mason").setup()
require("mason-lspconfig").setup()

--- auto complete
require("lsp/auto-complete")
-- hints
require("lsp/hints")

require("lsp/auto-format")

vim.lsp.enable("clangd")

vim.lsp.enable("dockerls")
vim.lsp.enable("docker_compose_language_service")
vim.lsp.enable("elixirls")
vim.lsp.enable("elp")
vim.lsp.enable("gopls")
vim.lsp.enable("hls")
vim.lsp.enable("html")
vim.lsp.enable("htmx")
vim.lsp.enable("jdtls")
vim.lsp.enable("jedi_language_server")
vim.lsp.enable("julials")
vim.lsp.enable("kotlin_language_server")
vim.lsp.enable("lua_ls")
vim.lsp.enable("ocamllsp")
vim.lsp.enable("omnisharp")
vim.lsp.enable("phpactor")
vim.lsp.enable("pyright")
vim.lsp.enable("r_language_server")
vim.lsp.enable("rust_analyzer")
vim.lsp.enable("texlab")
vim.lsp.enable("ts_ls")
vim.lsp.enable("tinymist")
vim.lsp.enable("zls")
